### ISSUE TITLE
您好，进您实验室读博咨询

### ISSUE THREAD

**Issue by Aleck16** [youjiangxu/seqvlad-pytorch#1]
师兄，您好！
我是河北工业大学16级计算机研究生，也在天津。有意向读您导师韩亚洪教授的博士，希望师兄能够给些建议。
本人qq邮箱
2292092213@qq.com

**Comment by youjiangxu** [comment]
韩老师 是一个　人很nice，又很专业的老师。
你有什么想咨询的可以发邮件到我邮箱 youjiangxu@gmail.com，或者直接联系韩老师，韩老师的个人主页是：http://cs.tju.edu.cn/faculty/hanyahong/index.html

另外，我们有一个在建的实验室主页，你也可以了解下：https://tjumm.github.io/

**Comment by Aleck16** [comment]
感谢感谢
