### ISSUE TITLE
import mc

### ISSUE THREAD

**Issue by ljiaogithub** [youjiangxu/seqvlad-pytorch#2]
Hi,       
when I ran your code, I ran into the following problem:

  File "/home/lj2017/seqvlad-pytorch/dataset.py", line 180, in __getitem__
    return self.get(record, segment_indices)
  File "/home/lj2017/seqvlad-pytorch/dataset.py", line 188, in get
    seg_imgs = self._load_image(record.path, p)
  File "/home/lj2017/seqvlad-pytorch/dataset.py", line 64, in _load_image
    mclient = mc.MemcachedClient.GetInstance(self.server_list_config_file, self.client_config_file)
NameError: name 'mc' is not defined

But,  at the beginning of the file  (dataset.py) , there are

#sys.path.insert(0, "/mnt/lustre/share/pymc")
#import mc

so, what is  'mc'?  thankyou.

**Comment by youjiangxu** [comment]
Hi, 
thank you for reporting the error.
you can ignore the 'mc' package and uncomment the error lines as follows:

```
#mclient = mc.MemcachedClient.GetInstance(self.server_list_config_file, self.client_config_file)
#value = mc.pyvector()
```

and you can read images from 'PIL' package, I will update the code soon.

**Comment by ljiaogithub** [comment]
OK, I'd love to read the updated code, thank you very much.
