### ISSUE TITLE
The best choice for your experiment?

### ISSUE THREAD

**Issue by ZealACMer** [youjiangxu/seqvlad-pytorch#4]
In the code, your model choices include ['seqvlad', 'bidirect', 'unshare_bidirect'], which is the choice you made in the experiment to obtain the best accuracy. Thank you very much.

**Comment by youjiangxu** [comment]
Hi,
Our method uses only the choice of 'seqvlad' on the action recognition
task. In addition, the choices of ['seqvlad', 'bidirect',
'unshare_bidirect'] are used in the task of video captioning and we find
that 'bidrect' could obtain a performance improvement in certain
circumstances.



Ao Li <notifications@github.com> 于2019年5月28日周二 下午3:13写道：

**Comment by ZealACMer** [comment]
Thank you very much for your prompt reply. So for the task of action recognition, your best choice in the experiments is **the self.seqvlad_type = 'seqvlad' in Class SeqVLAD**, is that right? Thank you for your attention.
![image](https://user-images.githubusercontent.com/16794553/58464768-de706300-8168-11e9-854a-795e200d05e4.png)
![image](https://user-images.githubusercontent.com/16794553/58464794-e9c38e80-8168-11e9-8842-58b733a82453.png)

**Comment by youjiangxu** [comment]
Yes， you are right.

Ao Li <notifications@github.com> 于2019年5月28日周二 下午4:52写道：

**Comment by ZealACMer** [comment]
Thanks a lot.
