### ISSUE TITLE
How many segments do you use during training?

### ISSUE THREAD

**Issue by ZealACMer** [youjiangxu/seqvlad-pytorch#5]
Hi, glad to meet you, my question is how many segments do you use during training process, 3 segments or 7 segments, thank you very much.

**Comment by youjiangxu** [comment]
Hi，
      does the 'segments' you mentioned above is the 'timesteps' argument ? or the same conception in the TSN?  
      In the SeqVLAD, we only use the tsn as our backbone network to extract feature from single frame image. As described in training stage (https://github.com/youjiangxu/seqvlad-pytorch#training), we use timestep=25 to train our SeqVLAD.
      May this information could help you! Thanks!

**Comment by ZealACMer** [comment]
Thank you very much for your prompt reply.
